apiVersion: ada-ubs/v1
kind: DataProduct
metadata:
  name: custom-kind-spike
  description: An example of a Backstage application.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
  name: data-product
  description: asd
